# conda env create -f environment.yml
name: lume-torch-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pydantic
  - numpy
  - pyyaml
  - botorch
  - mlflow

  # dev requirements
  - pytest
  - pre-commit
  - ruff

  # docs requirements
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - mkdocs-include-markdown-plugin
